postinst: do not exit if update-rc.d does not work
This is supposed to address:

| insserv: Service mysql has to be enabled to start service kamailio-proxy
| insserv: exiting now!
| update-rc.d: error: insserv rejected the script header
| dpkg: error processing kamailio (--configure):
|  subprocess installed post-installation script returned error exit status 1

Let's find out whether my approach works for CE + PRO as well,
might be a no-brainer with our custom ngcp stack so let's see
what we explore in release-trunk.

From: Michael Prokop <mprokop@sipwise.com>

diff --git a/pkg/kamailio/deb/squeeze/kamailio.postinst b/pkg/kamailio/deb/squeeze/kamailio.postinst
--- a/pkg/kamailio/deb/squeeze/kamailio.postinst
+++ b/pkg/kamailio/deb/squeeze/kamailio.postinst
@@ -21,7 +21,9 @@ initscript_handler() {
   [ -n "$1" ] || return 1
 
   if [ -x "/etc/init.d/$1" ]; then
-    update-rc.d "$1" defaults >/dev/null
+    if ! update-rc.d "$1" defaults >/dev/null ; then
+      echo "Warning: update-rc.d could not be executed, might be caused by mysql not available yet."
+    fi
     invoke-rc.d "$1" start || exit $?
   fi
 }
